### ISSUE TITLE
Call to undefined method stdClass::toArray()

### ISSUE THREAD

**Issue by groony-emmanuel** [rap2hpoutre/fast-excel#317]
Hello,
I could export a csv using data on the left one, but got an error using the right one.
![image](https://user-images.githubusercontent.com/81749007/220067398-13c39e7f-abf7-4a7b-95dd-25f358c8fe46.png)

This is the error

```
Error: Call to undefined method stdClass::toArray() in file /var/www/html/api/vendor/rap2hpoutre/fast-excel/src/Exportable.php on line 238

#0 /var/www/html/api/vendor/rap2hpoutre/fast-excel/src/Exportable.php(171): Rap2hpoutre\FastExcel\FastExcel-&gt;writeHeader(Object(OpenSpout\Writer\CSV\Writer), Object(stdClass))
#1 /var/www/html/api/vendor/rap2hpoutre/fast-excel/src/Exportable.php(112): Rap2hpoutre\FastExcel\FastExcel-&gt;writeRowsFromCollection(Object(OpenSpout\Writer\CSV\Writer), Object(Illuminate\Support\Collection), NULL)
#2 /var/www/html/api/vendor/rap2hpoutre/fast-excel/src/Exportable.php(49): Rap2hpoutre\FastExcel\FastExcel-&gt;exportOrDownload(&#039;/var/www/html/a...&#039;, &#039;openToFile&#039;, NULL)
#3 /var/www/html/api/app/Http/Controllers/Controller.php(93): Rap2hpoutre\FastExcel\FastExcel-&gt;export(&#039;/var/www/html/a...&#039;)
#4 /var/www/html/api/app/Http/Controllers/Api/ExportSettingController.php(36): App\Http\Controllers\Controller-&gt;exportData(Object(Illuminate\Http\Request))
#5 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\Api\ExportSettingController-&gt;index(Object(Illuminate\Http\Request))
#6 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller-&gt;callAction(&#039;index&#039;, Array)
#7 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\Routing\ControllerDispatcher-&gt;dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Api\ExportSettingController), &#039;index&#039;)
#8 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route-&gt;runController()
#9 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\Routing\Route-&gt;run()
#10 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(126): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(102): Illuminate\Routing\Middleware\ThrottleRequests-&gt;handleRequest(Object(Illuminate\Http\Request), Object(Closure), Array)
#15 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(54): Illuminate\Routing\Middleware\ThrottleRequests-&gt;handleRequestUsingNamedLimiter(Object(Illuminate\Http\Request), Object(Closure), &#039;api&#039;, Object(Closure))
#16 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\ThrottleRequests-&gt;handle(Object(Illuminate\Http\Request), Object(Closure), &#039;api&#039;)
#17 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#19 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\Routing\Router-&gt;runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#20 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\Routing\Router-&gt;runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#21 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\Routing\Router-&gt;dispatchToRoute(Object(Illuminate\Http\Request))
#22 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\Routing\Router-&gt;dispatch(Object(Illuminate\Http\Request))
#23 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#24 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\HandleCors-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#40 /var/www/html/api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter(Object(Illuminate\Http\Request))
#41 /var/www/html/api/public/index.php(52): Illuminate\Foundation\Http\Kernel-&gt;handle(Object(Illuminate\Http\Request))
#42 {main}
```

There is no special setting. Just using `(new FastExcel($list))->export(storage_path($filename));` 
Am I missing something? Anyone has a solution?

**Comment by elminson** [comment]
Verified fixed on the current version — exporting a collection of `stdClass`/objects (e.g. `DB::select()` results) now works without the `toArray()` error. This was a limitation of the older code at the time. Please `composer update rap2hpoutre/fast-excel`. Closing as resolved — reopen if you still hit it on the latest release.
